name: restaurant_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  android_alarm_manager_plus: ^2.0.5
  build_runner: ^2.1.9
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.0
  google_fonts: ^2.3.1
  http: 0.13.4
  intl: ^0.17.0
  mockito: ^5.1.0
  provider: ^6.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/404.png
    - assets/images/Resto.png
